import { Review } from "@/types";

function section(title: string, lines: string[]): string {
  if (lines.length === 0) return "";
  return `${title}\n${"-".repeat(title.length)}\n${lines.map((l) => `- ${l}`).join("\n")}\n\n`;
}

export function buildReportText(review: Review): string {
  const created = new Date(review.created_at).toLocaleString();

  let report = "";
  report += "RESUMEGAPAI — RESUME REVIEW REPORT\n";
  report += "===================================\n\n";
  report += `Generated: ${created}\n`;
  report += `Plan at time of review: ${review.plan_at_time}\n\n`;

  report += `OVERALL MATCH SCORE: ${review.match_score}/100\n`;
  report += `${review.summary}\n\n`;

  report += "SUB-SCORES\n----------\n";
  report += `ATS Score:          ${review.ats_score}/100\n`;
  report += `Readability:        ${review.readability_score}/100\n`;
  report += `Keyword Match:      ${review.keyword_match_score}/100\n`;
  report += `Impact Score:       ${review.impact_score}/100\n\n`;

  report += section("GAPS", review.gaps);
  report += section("WEAK AREAS", review.weak_areas);
  report += section("STRENGTHS", review.strengths);
  report += section("SUGGESTIONS", review.suggestions);

  if (review.plan_at_time === "pro" && review.interview_prep.length > 0) {
    report += "INTERVIEW READINESS SIMULATOR\n-----------------------------\n";
    review.interview_prep.forEach((item, i) => {
      report += `${i + 1}. Q: ${item.question}\n   A: ${item.answer_outline}\n\n`;
    });
  }

  report += "---\nGenerated by ResumeGapAI. Built for demonstration purposes.\n";
  return report;
}

export function downloadReport(review: Review): void {
  const text = buildReportText(review);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `resume-review-${review.id.slice(0, 8)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
